.TH mopyqtiv 1 "11 июля 2016"
.SH ИМЯ
mopyqtiv - Mouse oriented PyQt5 image viewer
Приспособленный под управление мышкой просмотрщик изображений
.SH КОМАНДНАЯ СТРОКА
.br
.B mopyqtiv
[-h] [файл]
.SH ОПИСАНИЕ
Просмотрщик изображений
.B mopyqtiv 
написан на python, с использованием библиотек PyQt пятой серии и PIL. Основные функции расчитаны на управление мышью. Так же в программе выполнен механизм для помощи в ручной сортировке изображений. Для удобства при просмотре можно использовать инструмент «лупа», менять масштаб а также вращать изображение.
.SH ОПЦИИ
.TP
-h
ключ для показа краткой справки
.TP
файл
программа может открыть изображения следующих форматов:
.PP
	*.bmp *.pbm *.pgm *.ppm *.xbm *.xpm *.jpg *.jpeg *.png *.gif
.SH УПРАВЛЕНИЕ
Для смены изображения следующее/предыдущее вращается колесико мыши. Если удерживать клавишу Ctrl, то вращением колесика мыши регулируется масштаб. С удержанием клавиши Shift колёсиком мыши можно вращать изображение.
.PP
При удержании клавиши Shift миниатюры пролистываются быстрее.
.PP
Для поворота изображения на 90 градусов вправо нажмите Ctrl+R, для поворота в лево Ctrl+L.
.PP
Если нажать одну из клавиш латинского алфавита, то программа попросит выбрать папку. Теперь эта папка привязана к нажатой клавише. При повторном нажатии текущее изображение будет перемещено в выбранную папку. Для освобождения нажмите Ctrl+клавиша. Поведение можно изменить правкой файла программы.
.SH НАСТРОЙКА
Программа настраивается правкой скрипта
.B /usr/bin/mopyqtiv
.SH АВТОР
Евгений
