.TH mopyqtiv 1 "19 июля 2016"
.SH ИМЯ
mopyqtiv - Mouse oriented PyQt5 image viewer
.PP
Приспособленный под управление мышкой просмотрщик изображений
.SH КОМАНДНАЯ СТРОКА
.B mopyqtiv
[-h] [файл]
.SH ОПИСАНИЕ
Просмотрщик изображений
.B mopyqtiv 
написан на python, с использованием библиотек PyQt пятой серии и PIL. Основные функции рассчитаны на управление мышью. Так же в программе выполнен механизм для помощи в ручной сортировке изображений. Для удобства при просмотре можно использовать инструмент «лупа», менять масштаб, а также вращать изображение.
.PP
По умолчанию работает программная отрисовка изображений. По желанию можно переключить в режим OpenGL.
.SH ОПЦИИ
.TP
-h
ключ для показа краткой справки
.TP
файл
программа может открыть изображения следующих форматов:
.PP
	  *.bmp *.pbm *.pgm *.ppm *.xbm *.xpm *.jpg *.jpeg *.png *.gif
.SH УПРАВЛЕНИЕ МЫШЬЮ
Для смены изображения следующее/предыдущее вращается колёсико мыши. Удержание левой кнопки на центральном изображении включает режим «лупа». Правая клавиша вызывает выпадающее меню.
.PP
При удержании левой кнопки колёсиком мыши вращается изображение. Удержание правой кнопки + колёсико управляет масштабом.
.PP
При однократном нажатии на колёсико картинка раскрывается в полную величину. Повторное нажатие вписывает изображение в габарит окна.
.SH УПРАВЛЕНИЕ МЫШЬ + КЛАВИАТУРА
 При удержании клавиши Ctrl вращением колёсика мыши регулируется масштаб. С удержанием клавиши Shift колёсиком мыши можно вращать изображение.
.PP
При удержании клавиши Shift миниатюры пролистываются быстрее.
.PP
Для поворота изображения на 90 градусов вправо нажмите Ctrl+R, для поворота влево Ctrl+L.
.PP
Если нажать одну из клавиш латинского алфавита, то программа попросит выбрать папку. Теперь эта папка привязана к нажатой клавише. При повторном нажатии текущее изображение будет скопировано/перемещено в выбранную папку. Для освобождения нажмите Ctrl+клавиша. Поведение зависит от настройки.
.SH НАСТРОЙКА
Программа настраивается правкой заголовка скрипта
.B /usr/bin/mopyqtiv
.SH АВТОР
Евгений
