.TH mopyqtiv 1 "20 июля 2016"
.SH ИМЯ
mopyqtiv \- Mouse oriented PyQt5 image viewer
.PP
Приспособленный под управление мышкой просмотрщик изображений
.SH КОМАНДНАЯ СТРОКА
.B mopyqtiv
[-h] [файл]
.SH ОПИСАНИЕ
Просмотрщик изображений
.B mopyqtiv 
написан на python, с использованием библиотек PyQt пятой серии и PIL. Основные функции рассчитаны на управление мышью. В программе выполнен механизм для помощи в ручной сортировке изображений. Для удобства при просмотре можно использовать инструмент «лупа», менять масштаб, а также вращать изображение.
.PP
По умолчанию работает программная отрисовка изображений. По желанию можно переключить в режим OpenGL.
.SH ОПЦИИ
.IP -h
ключ для показа краткой справки.
.IP файл
программа может открыть изображения следующих форматов:
.RS
*.bmp *.pbm *.pgm *.ppm *.xbm *.xpm *.jpg *.jpeg *.png *.gif
.SH УПРАВЛЕНИЕ МЫШЬЮ
.I режим 'лупа'
.RS
удержание левой кнопки на центральном изображении.
.RE
.PP
.I смена изображения следующее/предыдущее
.RS
колёсико мыши.
.RE
.PP
.I регулировка масштаба
.RS
правая кнопка + колёсико мыши.
.RE
.PP
.I вращение изображения
.RS
левая кнопка + колёсико мыши.
.RE
.PP
.I масштаб 1:1
.RS
нажатие на колёсико, повторное нажатие вписывает изображение в габариты окна.
.SH УПРАВЛЕНИЕ МЫШЬ + КЛАВИАТУРА
.I листание изображений
.RS
стрелки вверх/вниз/вправо/влево.
.RE
.PP
.I регулировка масштаба
.RS
Ctrl + колёсико мыши, PgUp/PgDown.
.RE
.PP
.I перемещение увеличенного изображения
.RS
стрелки вверх/вниз/вправо/влево.
.RE
.PP
.I вращение изображения
.RS
Shift + колёсико мыши, Shift + PgUp/PgDown.
.RE
.PP
.I удаление/перемещение в корзину текущего изображения
.RS
клавиша delete.
.RE
.PP
.I открытие окна выбора изображений
.RS
клавиша backspace.
.RE
.PP
.I выход из программы
.RS
клавиша escape.
.RE
.PP
.I сброс до начального вида изображения
.RS
клавиша пробела.
.RE
.PP
.I поворот изображения на 90 градусов
.RS
Ctrl+R для поворота по часовой стрелке, Ctrl+L для поворота против часовой стрелки.
.RE
.PP
Если нажать одну из клавиш латинского алфавита, то программа попросит выбрать папку. Теперь эта папка привязана к нажатой клавише. При повторном нажатии текущее изображение будет скопировано/перемещено в выбранную папку. Для освобождения нажмите Ctrl+клавиша. Поведение зависит от настройки.
.PP
При удержании клавиши Shift миниатюры пролистываются быстрее.
.SH НАСТРОЙКА
Для настройки программы правьте стандартный конфигурационный файл:
.RS
.IP /etc/mopyqtiv/config.ini
.RE
.PP
либо скопируйте его и правьте в домашнем каталоге по следующему пути:
.RS
.IP ~/.config/mopyqtiv/config.ini
.SH АВТОР
Евгений
